## Travis CI Integration

language: csharp
solution: Source/EasyNetQ.Rx.sln

script:
  - xbuild /p:Configuration=Release Source/EasyNetQ.Rx.sln
  - mono Source/packages/NUnit.ConsoleRunner.*/tools/nunit3-console.exe Source/EasyNetQ.Rx.Tests/bin/Release/EasyNetQ.Rx.Tests.dll