## Travis CI Integration

language: csharp
solution: Source/EasyNetQ.Rx.sln
script:
  - xbuild /p:Configuration=Release Source/EasyNetQ.Rx.sln
  - mono ./packages/NUnit.Runners.*/tools/nunit-console.exe Source/EasyNetQ.Rx.Tests/bin/Debug/EasyNetQ.Rx.Tests.dll